### ISSUE TITLE
예제 챕터7 자언어 단어단위 생성 오류

### ISSUE THREAD

**Issue by hyeonjunni** [wikibook/tf2#11]
코랩 코드를 그대로 파이참 환경에서 실행 시켰을때 
Function call stack:
distributed_function -> distributed_function -> distributed_function
와 같은 에러가 표시 됩니다.

**Comment by greentec** [comment]
안녕하세요.
말씀주신 문제가 코랩에서는 재현되지 않는 것을 확인했습니다.

사용하시는 파이참 환경에 대해서는 제가 잘 알지 못하지만, 구글링을 해보니 적어주신 에러 메시지가 GPU 할당 문제일 가능성이 있어 보입니다.
https://mickael-k.tistory.com/32
혹시 위의 페이지에 나온대로 GPU를 설정하신 후에도 문제가 재발한다면 다시 말씀부탁드립니다.
그리고 정확한 문제 재현을 위해 현재 사용하시는 텐서플로 버전을 알려주시면 좋을 것 같습니다.

감사합니다.
