### ISSUE TITLE
챕터10 코드 실행오류

### ISSUE THREAD

**Issue by jinhj** [wikibook/tf2#13]
# 10.4 랜덤 행동 에이전트의 환경 실행 결과 확인
env = wrap_env(gym.make('MountainCar-v0'))
env.reset()

score = 0
step = 0
while True:
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    score += reward
    step += 1
    
    if done:
        break

print('score:', score)
print('step:', step)
env.close()
show_video()

위 코드 실행 시 아래와 같은 오류가 발생합니다.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-0bcfd09c79cf> in <module>()
      1 # 10.4 랜덤 행동 에이전트의 환경 실행 결과 확인
      2 env = wrap_env(gym.make('MountainCar-v0'))
----> 3 env.reset()
      4 
      5 score = 0

6 frames
/usr/local/lib/python3.6/dist-packages/gym/wrappers/monitor.py in reset(self, **kwargs)
     37         self._before_reset()
     38         observation = self.env.reset(**kwargs)
---> 39         self._after_reset(observation)
     40 
     41         return observation

/usr/local/lib/python3.6/dist-packages/gym/wrappers/monitor.py in _after_reset(self, observation)
    183         self.stats_recorder.after_reset(observation)
    184 
--> 185         self.reset_video_recorder()
    186 
    187         # Bump *after* all reset activity has finished

/usr/local/lib/python3.6/dist-packages/gym/wrappers/monitor.py in reset_video_recorder(self)
    204             enabled=self._video_enabled(),
    205         )
--> 206         self.video_recorder.capture_frame()
    207 
    208     def _close_video_recorder(self):

/usr/local/lib/python3.6/dist-packages/gym/wrappers/monitoring/video_recorder.py in capture_frame(self)
     99 
    100         render_mode = 'ansi' if self.ansi_mode else 'rgb_array'
--> 101         frame = self.env.render(mode=render_mode)
    102 
    103         if frame is None:

/usr/local/lib/python3.6/dist-packages/gym/core.py in render(self, mode, **kwargs)
    231 
    232     def render(self, mode='human', **kwargs):
--> 233         return self.env.render(mode, **kwargs)
    234 
    235     def close(self):

/usr/local/lib/python3.6/dist-packages/gym/envs/classic_control/mountain_car.py in render(self, mode)
    117         self.cartrans.set_rotation(math.cos(3 * pos))
    118 
--> 119         return self.viewer.render(return_rgb_array = mode=='rgb_array')
    120 
    121     def get_keys_to_action(self):

/usr/local/lib/python3.6/dist-packages/gym/envs/classic_control/rendering.py in render(self, return_rgb_array)
    113             buffer = pyglet.image.get_buffer_manager().get_color_buffer()
    114             image_data = buffer.get_image_data()
--> 115             arr = np.frombuffer(image_data.get_data(), dtype=np.uint8)
    116             # In https://github.com/openai/gym-http-api/issues/2, we
    117             # discovered that someone using Xmonad on Arch was having

TypeError: get_data() missing 2 required positional arguments: 'format' and 'pitch'

**Comment by greentec** [comment]
안녕하세요.
오류를 제보해주셔서 감사드립니다.
라이브러리 중 pyglet의 버전을 다운시켜서 gym과 버전이 맞지 않게 된 것이 원인으로, 해당 문제를 수정했습니다.
감사합니다.

**Comment by greentec** [comment]
- [x] google colab에 변경사항 적용
- [x] github에 변경사항 적용
