### ISSUE TITLE
예제7.41 실행오류

### ISSUE THREAD

**Issue by sjleergb** [wikibook/tf2#15]
주피터노트북으로 코딩중입니다.
예제7.40까지는 되는데 7.41 실행하면

Train for 533 steps
Epoch 1/50

이렇게 나오고 연산이 더이상 안되고 멈춰버립니다.
restrat kernel 해도 마찬가지고요

**Comment by greentec** [comment]
안녕하세요.
7장 순환신경망부터는 모델의 크기가 매우 커지기 때문에, 학습을 위해서는 많은 메모리와 가급적 고사양의 GPU를 필요로 합니다.
예제 7.40은 모델을 정의하는 과정이기 때문에 실행에 문제가 없었던 것 같지만 예제 7.41은 실제로 모델을 학습시키는 부분으로, 이때 사용하시는 GPU의 사양이 부족할 경우에는 말씀주신 것처럼 학습이 멈출 수 있습니다.
책에서 제공하는 예제인 [구글 코랩](https://colab.research.google.com/drive/1J3isaEuS-WGThRNks4VxJ50oL-t-EG7W?usp=sharing)에서 시도해보시는 것이 현재로서는 가장 나은 대안일 것 같습니다.

**Comment by sjleergb** [comment]
답변 감사드립니다. 제가 노트북으로 하다보니 cpu버전 아나콘다 사용중이었는데 구글 코랩으로 시도해보니4-5시간 경과후 학습 완료됐습니다.
