### ISSUE TITLE
p258 예제8.9 unzip error

### ISSUE THREAD

**Issue by sjleergb** [wikibook/tf2#16]
colab 에서
!unzip train.zip
!unzip labels.csv.zip 입력시

train.zip 은 정상적으로 압축풀리나
labels.csv.zip 은 "cannot find or open labels.csv.zip, labels.csv.zip.zip or labels.csv.zip.ZIP." 메세지가 출력됩니다. Chapter8_20200408수정.ipynb 에서도 같은 문제 발견됩니다.

**Comment by greentec** [comment]
안녕하세요.
원래 코드와 달리 임시로 수정된 `Chapter8_20200408수정.ipynb`에서는 `labels.csv.zip` 대신에 `labels.csv`를 불러오기 때문에 `!unzip labels.csv.zip`은 실행하지 않아도 되는 명령어입니다. 제가 실수로 주석처리를 하지 않았네요.
제보 감사드리며 해당 라인을 주석처리하도록 하겠습니다.

**Comment by greentec** [comment]
- [x] colab 코드 수정
- [x] github 코드 수정
