### ISSUE TITLE
예제 8-22 오류

### ISSUE THREAD

**Issue by sjleergb** [wikibook/tf2#17]
NameError: name 'train_X' is not defined

코랩 코드 그대로 복사해서 실행했는데 위와같은 오류가 나왔습니다.

예제8.19에서
steps_per_epoch = int(7718/32)
history = model.fit_generator(train_generator, validation_data=valid_generator, epochs=10, steps_per_epoch=steps_per_epoch) 

예제8.22에서
history = model.fit(train_X, train_Y, epochs=10, validation_split=0.25, batch_size=32)

모델학습이 다르게 적용되었는데 이유가 궁금합니다.

**Comment by greentec** [comment]
안녕하세요.
이 부분은 이 저장소의 README.md에 나와있는 `[2020.04.08] 263p. 예제 8.16의 OOM(Out Of Memory) 발생 문제.` 로 인한 수정이 미처 반영되지 않았던 부분인 것 같습니다.
제보 감사드리며 예제 8.22의 학습 부분도 예제 8.19처럼 `mode.fit()` 대신 `model.fit_generator()` 함수를 사용하도록 수정하겠습니다.

**Comment by greentec** [comment]
- [x] colab 코드 수정
- [x] github 코드 수정
