### ISSUE TITLE
p.245예제8.3 실행오류 질문입니다.

### ISSUE THREAD

**Issue by songlee1** [wikibook/tf2#19]
for idx, item in enumerate(data_root.iterdir()):
    print(item)
    if idx == 9:
        break
를 실행시켰을 때 정상적으로 코딩이 실행되지 않습니다.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-7be82ef0ce58> in <module>()
      1 # 8.3 디렉토리 출력
----> 2 for idx, item in enumerate(data_root.iterdir()):
      3     print(item)
      4     if idx == 9:
      5         break

1 frames
/usr/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    385         @functools.wraps(strfunc)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)
    389 

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/datasets/imagenetv2-topimages'

**Comment by HajeongKimm** [comment]
저도 이 부분에서 막혀서 진행이 안됩니다.. 
어떻게 해결해야하나요?

**Comment by greentec** [comment]
안녕하세요.
원본 데이터를 제공하는 쪽에서 폴더 이름을 바꿔서 생긴 이슈입니다.
colab과 github에서 수정 후 close하도록 하겠습니다.
학습에 불편을 드려 죄송합니다.

**Comment by greentec** [comment]
- [x] colab 코드 수정
- [x] github 코드 수정

**Comment by JongwonMoon** [comment]
저도 이부분에서 똑같은 오류가 발생합니다. 
그리고 코드 수정부분을 볼 수가 없습니다.

**Comment by songlee1** [comment]
저자께서 코드를 수정해주신 후 저는 잘 됐습니다. 수정본 찾아보신 후 안되시면 저자께 다시 질문해보시는걸 추천드립니다
​
-----Original Message-----

**Comment by JongwonMoon** [comment]
수정본은 어디서 들어갈 수 있나요....??

**Comment by songlee1** [comment]
제가 했을때는 원본이 같이 수정되어 수정되었다는 설명이 있었던걸로 기억납니다. 공부한지 시간이 좀 되서 잘은 생각이 안나네요. 죄송합니다
​
-----Original Message-----
