### ISSUE TITLE
p448 예제10.39 실행오류

### ISSUE THREAD

**Issue by sjleergb** [wikibook/tf2#20]
colab GPU로 코딩중입니다.
예제10.39 실행시 score 9000정도에서 시스템이 다운이 됩니다. 약 6시간 정도 지났구요.
어떻게 해결해야 할까요?

**Comment by greentec** [comment]
안녕하세요. 
혹시 max_episodes를 10001이 아닌 좀 더 큰 수치로 조정하셨는지 확인이 필요할 것 같습니다. colab은 메모리 문제가 있기 때문에 너무 큰 episode를 실행하려고 하면 메모리 부족으로 시스템이 다운될 수 있습니다.
참고로 오늘 제가 예제 10.39를 colab pro에서 실행했을 때는 1시간 40분 정도 소요된 후 실행이 완료되었습니다. 책을 집필할 때에는 colab 무료 버전에서도 괜찮은 GPU를 사용할 수 있었지만 현재는 유료 버전에서만 해당 GPU를 제공하는 것으로 알고 있습니다. 혹시 유료 버전과 무료 버전의 차이에서 기인하는 문제라면 코드와 책에 안내된 max_episodes를 조정해야할 것 같습니다.

**Comment by sjleergb** [comment]
책에 있는 code 그대로 사용해서 10001 적용했고 colab은 무료버전 사용했으며 두번 실행해봤는데 완료가 되지 않고 다운되었습니다. episode 5001 정도로 줄이니깐 실행은 되는데 결과가 텍스트 만큼은 만족스럽지 않습니다.
