### ISSUE TITLE
page 385 예제 9.45 오류 입니다

### ISSUE THREAD

**Issue by capcoon** [wikibook/tf2#22]
9장의 385 페이지 예제 9.45 "테스트 이미지 분할 확인"을 실행하면 그림이 출력되지 않고 자꾸 오류가 납니다.
아래와 같은 오류 메시지가 나오며 그림은 재구성된 마스크 이미지가 출력되지 않습니다.
코드상에 오류가 있는지 확인 부탁드립니다.

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in squeeze(a, axis)
   1476     try:
-> 1477         squeeze = a.squeeze
   1478     except AttributeError:

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'squeeze'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
2 frames
<__array_function__ internals> in squeeze(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     45     except AttributeError:
     46         wrap = None
---> 47     result = getattr(asarray(obj), method)(*args, **kwds)
     48     if wrap:
     49         if not isinstance(result, mu.ndarray):

ValueError: cannot select an axis to squeeze out which has size not equal to one 

![image](https://user-images.githubusercontent.com/16862218/93714871-71c07980-fba0-11ea-9070-d4f741cde9f3.png)

**Comment by greentec** [comment]
안녕하세요.
문의하신 코드는 구글 코랩에서는 정상적으로 실행되고 있는 부분입니다.
코랩에서 실행 후에도 오류가 발생하시는지 확인 부탁드립니다.
[Chapter9.ipynb_9.5단원 문제 해결을 위한 임시 파일](https://colab.research.google.com/drive/11EynfkjBA4bx5hK2lHWAcCF6HCVL2Bi4?usp=sharing)

**Comment by capcoon** [comment]
코랩에서 정상 작동되는것 확인했습니다. 고맙습니다
