### ISSUE TITLE
예제 8.2 ImageNet 로드 오류

### ISSUE THREAD

**Issue by ewlkkf** [wikibook/tf2#27]
### **코드**
```
# 8.2 ImageNetV2-TopImages 불러오기
import os
import pathlib
content_data_url = '/content/sample_data'
data_root_orig = tf.keras.utils.get_file('imagenetV2', 'https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-topimages.tar.gz', cache_dir=content_data_url, extract=True)
data_root = pathlib.Path(content_data_url + '/datasets/imagenetv2-top-images-format-val')
print(data_root)
```

### **증상**
Downloading data from https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-topimages.tar.gz

HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    277       try:
--> 278         urlretrieve(origin, fpath, dl_progress)
    279       except HTTPError as e:

8 frames
HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    278         urlretrieve(origin, fpath, dl_progress)
    279       except HTTPError as e:
--> 280         raise Exception(error_msg.format(origin, e.code, e.msg))
    281       except URLError as e:
    282         raise Exception(error_msg.format(origin, e.errno, e.reason))

Exception: URL fetch failure on https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-topimages.tar.gz: 403 -- Forbidden

링크가 아예 접속이 안 됩니다. 막힌 것 같습니다.

**Comment by greentec** [comment]
현재 원본 이미지를 올린 링크를 이동 중이라고 합니다.
https://github.com/modestyachts/ImageNetV2/issues/5
이동 작업 중에는 해당 리소스에 접근이 어려울 것 같습니다. 이동이 완료되는대로 혹시 링크가 수정된다면 업데이트하도록 하겠습니다. 제보해주셔서 감사합니다.

**Comment by greentec** [comment]
해당 데이터의 경로가 이동된 것을 확인, 정상적으로 다운로드하였으나 폴더 이름 등이 수정되어 관련된 수정 작업을 진행했습니다. 제보에 다시한번 감사드립니다.

**Comment by greentec** [comment]
- [x] colab 코드 수정
- [x] github 코드 수정
