### ISSUE TITLE
예제 8.2 ImageNetV2-TopImages 불러오기 오류 해결

### ISSUE THREAD

**Issue by GyungGeunPark** [wikibook/tf2#28]
import os
import pathlib
content_data_url = '/content/sample_data'
data_root_orig = tf.keras.utils.get_file('imagenetV2', 'https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-top-images.tar.gz', cache_subdir='datasets',cache_dir=content_data_url, extract=True) # cache_subdir='datasets' 압축 풀 폴더 생성
data_root = pathlib.Path(content_data_url + '/datasets/imagenetv2-top-images-format-val') # imagenet에 v2 추가 (폴더이름이 안맞아 디렉터리 불러오기 오류)
print(data_root)

**Comment by JaeYeoungPark** [comment]
> import os
> import pathlib
> content_data_url = '/content/sample_data'
> data_root_orig = tf.keras.utils.get_file('imagenetV2', 'https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-top-images.tar.gz', cache_subdir='datasets',cache_dir=content_data_url, extract=True) # cache_subdir='datasets' 압축 풀 폴더 생성
> data_root = pathlib.Path(content_data_url + '/datasets/imagenetv2-top-images-format-val') # imagenet에 v2 추가 (폴더이름이 안맞아 디렉터리 불러오기 오류)
> print(data_root)

**Comment by greentec** [comment]
안녕하세요.
해당 문제는 https://github.com/wikibook/tf2/issues/27 에서 해결된 문제로, 수정된 코드가 github과 colab에 적용되었습니다.

감사합니다.
