### ISSUE TITLE
p245 예제 8.3 디렉토리 출력 이슈

### ISSUE THREAD

**Issue by routee90** [wikibook/tf2#30]
안녕하세요.

# 8.3 디렉토리 출력
for idx, item in enumerate(data_root.iterdir()):
    print(item)
    if idx == 9:
        break

부분에서 해당 에러가 발생하는 것으로 보아 디렉토리 경로가 변경된 것으로 보여집니다.

============================================================
/content/sample_data/datasets/imagenet-top-images-format-val

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-9-c44961fa026c> in <module>()
     24 #print(enumerate(data_root.iterdir()))
     25 
---> 26 for idx, item in enumerate(data_root.iterdir()):
     27     print(item)
     28     if idx == 9:

1 frames

/usr/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    385         @functools.wraps(strfunc)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)
    389 

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/datasets/imagenet-top-images-format-val'
==========================================================

확인해주시고, 정오표에 추가해주시면 좋을 것 같습니다.

추가) 
==========================================================
data_root = pathlib.Path(content_data_url + '/datasets/imagenet-top-images-format-val')
==========================================================

==>

==========================================================
data_root = pathlib.Path(content_data_url + '/datasets/imagenetv2-top-images-format-val')
==========================================================

로 변경하면 정상 동작합니다.

**Comment by greentec** [comment]
안녕하세요.
#19 에서 발생했던 문제인데 재발한 것 같습니다.
원인은 데이터 제공자 측에서 폴더와 파일 이름을 바꿔서 발생한 것으로, 문제 해결을 위해 폴더 이름을 `glob` 으로 자동으로 찾도록 했습니다.
colab과 github에서 수정 후 close하도록 하겠습니다.
학습에 불편을 드려 죄송합니다.

**Comment by greentec** [comment]
- [x] github 수정
- [x] colab 수정
