### ISSUE TITLE
책을 다 읽고 궁금한 부분이 생겨 여쭤봅니다.

### ISSUE THREAD

**Issue by routee90** [wikibook/tf2#33]
안녕하세요. 개발하고 싶은 아이템이 생겨 1인 개발에 도전하고 있는 구독자입니다.

개발 내용과 관련하여 tensorflow hub에서 미리 1000장의 사전 학습된 내용에 없는 내용만을 제가 직접 학습시켜야 하는 상황인데요, 일반적으로 각각의 이미지를 학습시키기 위해 몇 장 정도 이미지를 준비하는지(교재에서 언급하셨던 '표본이 적을 경우 사용하는 방법'을 제외한 이미지 개수) 궁금합니다.

답변해 주신다면 큰 도움이 될 것 같습니다.
감사합니다. 번창하세요.

**Comment by greentec** [comment]
안녕하세요.
질문 주신 부분에서 `각각`은 서로 다른 label class를 의미하는 것으로 이해했습니다. 이에 대해서 제 생각은 최소 `몇백 장` 이기는 했는데, 찾아보니 [Pete Warden](https://github.com/petewarden)의 [좋은 글](https://petewarden.com/2017/12/14/how-many-images-do-you-need-to-train-a-neural-network/)이 있어서 공유드립니다.

요약
- ImageNet을 보니 각 class당 1000장이 필요하다.
- 같은 도메인에 transfer learning을 시도할 경우는 10~20장으로도 충분할 수 있다.
- 대표성을 가진 이미지인 경우에는 이미지가 좀 더 적게 필요할 수 있다.

이 글이 2017년에 쓰였지만 아직 유효한 내용인 것 같습니다. 추가로 의견 있으시면 말씀 부탁드립니다. 감사합니다.
