### ISSUE TITLE
책 챕터 5 코드 오류

### ISSUE THREAD

**Issue by Sopiro** [wikibook/tf2#5]
116p ex5.8에 loss func.를 saprs_categorical_crossentropy를 사용하라고 나오는데 label이 one-hot이라 categorical_crossentropy로 바꿔야되네용.

**Comment by greentec** [comment]
안녕하세요.
말씀주신대로 오타가 맞습니다. 코랩과 깃허브, [출판사 홈페이지의 정오표](https://wikibook.co.kr/tf2/)에는 해당 내용이 수정되어 있습니다.
감사합니다.
