### ISSUE TITLE
예제4.4 실행시 아래와 같은 error가 발생합니다.

### ISSUE THREAD

**Issue by gidarim** [wikibook/tf2#7]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'RefVariable' object has no attribute '_id'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-13-b0ba9c8b5fb2> in <module>()
     19 for i in range(1000):
     20     # 잔차의 제곱의 평균을 최소화(minimize)합니다.
---> 21     optimizer.minimize(compute_loss, var_list=[a,b])
     22 
     23     if i % 100 == 99:

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/tape.py in watch(tape, tensor)
     57 def watch(tape, tensor):
     58   """Marks this tensor to be watched by the given tape."""
---> 59   pywrap_tensorflow.TFE_Py_TapeWatch(tape._tape, tensor)  # pylint: disable=protected-access
     60 
     61 

SystemError: <built-in function TFE_Py_TapeWatch> returned a result with an error set

**Comment by greentec** [comment]
안녕하세요.
구글 코랩에 올라온 예제 파일에서 정상 실행되는 것을 확인했습니다.
올려주신 에러 메시지로 검색해보니 다음과 같은 응답이 있어서 첨부합니다.
[https://stackoverflow.com/questions/57250679/refvariable-object-has-no-attribute-id](https://stackoverflow.com/questions/57250679/refvariable-object-has-no-attribute-id)
아마도 텐서플로의 Eager Execution이 꺼져 있어서 발생하는 문제 같습니다만, Eager Execution은 텐서플로 2 이상에서는 기본적으로 켜져 있는 상태이기 때문에, 텐서플로 1.x 버전을 사용하고 계신 것이 아닌가 생각됩니다.
구글 코랩에서 정상 동작하므로 일단 이 이슈는 닫도록 하겠습니다. 추가로 문의사항이 있으시면 말씀 부탁드립니다.
